spring:
    redis:
      host: 192.168.3.23
      port: 6379
      password: 123456
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0ms